[Test] Add translations
chinosk6/GakumasTranslationData pull request #7
Opened 2024-07-04 06:20 UTC by fecent

尝试增加翻译

2024-07-04 06:43 UTC, Badmingrams commented
这么做是对的。
不过我看到你把所有的サポートカード都改成了辅助卡。这有什么理由吗？从我这里来看没有什么明显的优劣之分。

PS：generic string翻译正在重构，一方面是会加入一个缩水的正则表达式来简化部分字符串的翻译，一方面是有一个新的子项目用于优化generic string的管理成本

2024-07-04 07:02 UTC, Badmingrams commented
看起来是辅助卡稍好一点。你可以也修改一下 https://github.com/imas-tools/GakumasPreTranslation/blob/main/etc/translated.json 这个文件。我一起merge进来

2024-07-04 07:33 UTC, Badmingrams commented
另一个项目在这边 https://github.com/imas-tools/gakumas-genric-source-strings/tree/main/data 包含的字符串会更多一些。如果需要翻译字符串可以从这里面找然后翻译，提交到这里，之后另一边完成后我会做迁移

2024-07-04 07:54 UTC, Badmingrams commented
"このサポートカードのレッスンサポート発生率を": "此辅助卡的课程支援发生率"

我确认了一下这条翻译。从这条翻译看感觉还是就当作支援卡翻译比较好

2024-07-04 08:14 UTC, Badmingrams commented
事实上是两者都有。如果没有明显的优劣我倾向于选择一致的用字以及保持现状不变。pretranslation那边的更改我也暂且先revert

2024-07-04 08:15 UTC, Badmingrams requested changes

2024-07-04 08:37 UTC, Badmingrams commented
> 对了我想到你说的正则表达式，我看了那个完整的generic.json，里面是按假名顺序排的，这个有个问题，如果按这个顺序排的话
> 
> "アイドル": "偶像", "アイドル衣装：": "偶像衣服：",
> 
> 这样会不会先匹配到偶像，然后后面的アイドル衣装就匹配不到了，被替换为偶像衣装：

不会。实现的是一个权衡了性能的拼接字符串版本。会优先整体替换，之后根据特定字符拆分，拆分后每部分还是整体替换。アイドル衣装里面不包含特殊字符，所以不会被拆分，只有整体替换

2024-07-05 02:05 UTC, darwintree commented
> 那我就放心了，我按完整的generic.json继续翻译吧，不过里面好像还有少一部分的字符。
> 
> 另外这个完整的generic.json是否可以直接用ai直接批量翻译
> 
> 好像这个文件要完整翻好才能用，刚刚试了直接替换无效了

本来就是用ai批量翻译+校对的。之后的项目里会集成这一部分。直接替换无效是需要启用插件的强制替换资源。

2024-07-05 17:27 UTC, closed without merging